version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    env_file: '.env'
  rabbitmq:
    image: 'rabbitmq:3.7.3-management'
    container_name: some-rabbit
    env_file: '.env'
    ports:
      - '5672:5672'
      - '15672:15672'
  migration:
    build: .
    env_file: '.env'
    command: ['/code/wait-for-it.sh', 'db:3306', '--', 'python', 'manage.py', 'migrate']
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    command: ['/code/wait-for-it.sh', 'db:3306', '--', 'python', '/code/server.py']
    volumes:
      - .:/code
    ports:
      - "9808:9808"
    env_file: '.env'
    environment:
      - VIRTUAL_HOST=web.local
    depends_on:
      - db
      - migration
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: '.env'
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions
  celery_worker:
    build: .
    env_file: '.env'
    environment:
      - C_FORCE_ROOT=1
    command: 'python -m celery -A mysite worker -l info'
    volumes_from:
      - web
    depends_on:
      - rabbitmq
      - phpmyadmin
      - migration
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
